### ISSUE TITLE
ESPConnectClass::erase() does not clear wifi credentials on ESP8266

### ISSUE THREAD

**Issue by musicman944** [ayushsharma82/ESPConnect#11]
This can be resolved by updating the ESP8266 section of ESPConnectClass::erase() with the following code to clear out the saved credentials:
  #if defined(ESP8266)
    // -----------  Added this section to erase stored wifi credentials   --------------------
    int ok = 0;
    struct station_config	config = {};
    memset(&config.ssid, 0, sizeof(config.ssid));
    memset(&config.password, 0, sizeof(config.password));
    config.bssid_set = false;
    ok = wifi_station_set_config(&config);
    // -----------------------------------------------------------------------------------------
    return WiFi.disconnect(true);

**Comment by ayushsharma82** [comment]
Great! Thanks for providing a solution.
Would you like to open a pull request? This will add you as an official contributor to this project for everybody to see :)

**Comment by musicman944** [comment]
Sure, I'll be glad to do so.  I'm new to GitHub pull requests so I hope I did it right.

**Comment by musicman944** [comment]
Did the pull request work?

**Comment by ayushsharma82** [comment]
Merged and released under v1.0.4

Thanks! 🎉
