### ISSUE TITLE
extra examples for server to clients communications

### ISSUE THREAD

**Issue by dsyleixa** [ayushsharma82/ESPConnect#2]
hello,
your lib seems to be very handsome, simplifying a lot of the complicated WiFi connection!
Would it be possible to provide extra examples for server to clients communications, e.g.
- 1 ino file for a server (e.g., ESP32)
- 1 ino file for a client (e.g., ESP8266)
- both codes showing communications to send data strings there and back, e.g. sensor data from the client to the server (showing it up on a hostet html website), and seding data from the server back to the client (showing it up in the serial monitor)?

**Comment by ayushsharma82** [comment]
Hi,
Thanks for your suggestions but those don't come under the scope of this library.

You'll have figure that part yourself.
