### ISSUE TITLE
List of WiFi networks cannot be seen if there is one of following charcters in one of the scanned SSIDs: " ' \

### ISSUE THREAD

**Issue by jumd** [ayushsharma82/ESPConnect#3]
The issue is solved by adding escape characters:

        String ssid = WiFi.SSID(i);
        ssid.replace("\\","\\\\");
        ssid.replace("\"","\\\"");

        json+="{";
        json+="\"name\":\""+ssid+"\",";

**Comment by ayushsharma82** [comment]
Thanks for reporting the issue & also providing a solution to the problem! Cheers 🍻

I'll create a pull request in a minute.

**Comment by ayushsharma82** [comment]
Fixed in 1b7258c

Now live with v1.0.1
