### ISSUE TITLE
"Failed to connect to WiFi" is shown on serial terminal even if connected to WiFi STA successfully

### ISSUE THREAD

**Issue by aikboon2002** [ayushsharma82/ESPConnect#6]
"Failed to connect to WiFi" is shown on serial terminal when you have pre-configured ssid and password and connected to WiFi STA successfully.

Line #232 of ESPConnect.cpp should return true instead of false.
// Start Captive Portal if not connected to STA
  if(WiFi.status() != WL_CONNECTED){
    // Start captive portal
    return start_portal();
  }else{
    ESPCONNECT_SERIAL("Connected to STA\n");
    return false; => Line#232 should return true
  }

**Comment by ayushsharma82** [comment]
Fixed with v1.0.3 release.
